maud_macros/src/render.rs
Rust seems to need this now.
rustc 1.0.0-nightly (d17d6e7f1 2015-04-02) (built 2015-04-03)
=> Rust upgrade (seems to need a Clone with a Copy).

maud_macros/src/parse.rs, maud_macros/tests/tests.rs
Makes it easier when you want to reference structs/functions in other modules without importing them into the local context. E.g. just using `html!(w, $maud::PreEscaped("value"))` instead of having to `use maud::PreEscaped`.
=> Allow path lookups in un-delimited splices

maud_macros/src/parse.rs, maud_macros/tests/tests.rs
This is similar to how [slim](http://slim-lang.com) works, very useful when you're using a class heavy css framework. An example from the bootstrap docs
```
div class="input-group" {
span class="input-group-addon" { "$" }
input type="text" class="form-control" aria-label="Amount (to the nearest dollar)" { }
span class="input-group-addon" { ".00" } 
}
```
becomes
```
.input-group {
span.input-group-addon { "$" }
input.form-control type="text" aria-label="Amount (to the nearest dollar)" { }
span.input-group-addon { ".00" } 
}
```
=> Add a shorthand syntax to define element classes

maud/src/lib.rs, maud_macros/src/parse.rs, maud_macros/src/render.rs, maud_macros/tests/tests.rs
* Change `$` -> `^` and `#` -> `@`.
* Add in support for render by move (with test showing it will still default to by-ref if needed).
* Add in some more tests.
* Remove symbol from `#else` (I guess this could break using an element called `else`, but who's gonna do that?)
Fixes #21, #24 and #26.
=> Change symbology

benchmarks/benches/complicated_maud.rs
As part of #49 I've extracted a simple but still somewhat more involved example.
If you would like anything else to be added or more examples I could do that
=> Add complicated Maud benchmark

maud_macros/src/parse.rs, maud_macros/src/render.rs, maud_macros/tests/control_structures.rs
Fixes #51.
@lfairy let me know if I missed anything! I mostly copied the `@if` code like you had suggested.
=> Add support for `@while` and `@while let`.

maud/Cargo.toml
I'm trying to use this library with Rocket, so I updated the dependency to version 0.2.0.
=> Update Rocket dependency to version 0.2.0

maud_extras/lib.rs
Adding convenience struct for generating meta tags that contain `property` instead of `name`.
Useful in a context of open graph tags http://ogp.me/.
=> Add MetaProperty element

CHANGELOG.md, maud/Cargo.toml, maud/src/lib.rs
Also fixes diff links in CHANGELOG.md. Releasing would require bumping `maud` and `maud_macros` to 0.17.0 due to `Responder::respond(self)` becoming `Responder::respond_to(self, &Request)`.
=> Update to Rocket 0.3

.travis.yml, Cargo.toml, maud/Cargo.toml, maud/src/lib.rs, maud/tests/basic_syntax.rs, maud/tests/control_structures.rs, maud/tests/misc.rs, maud/tests/splices.rs, maud_extras/Cargo.toml, maud_extras/lib.rs, maud_htmlescape/Cargo.toml, maud_htmlescape/lib.rs, maud_macros/Cargo.toml, maud_macros/src/lib.rs, maud_macros/src/parse.rs, maud_macros/src/render.rs
This changes how Maud is imported.
Users will need to change their code from this:
```rust
// Maud 0.16
#![feature(plugin)]
#![plugin(maud_macros)]
extern crate maud;
```
to this:
```rust
// Maud 0.17
#![feature(proc_macro)]
extern crate maud;
use maud::html;
```
Note the lack of `#![plugin]` or `#[macro_use]` attributes -- the new proc macro system allows for importing macros in the same way as any other item.
Closes #92
=> Port to new proc macro interface

maud_extras/lib.rs
Adding meta robots tags helper, I can reuse MetaProperty if needed.
=> Add meta robots tags helper

maud/src/lib.rs
=> Add `Clone` and `Copy` impl to `PreEscaped` via derive

benchmarks/Cargo.lock, benchmarks/Cargo.toml, benchmarks/benches/complicated_maud.rs, benchmarks/benches/handlebars.rs, benchmarks/benches/maud.rs, benchmarks/benches/tera.rs
This PR makes benchmarkers dependencies are upgraded and broken cases are now fixed on latest template engines.
----------
| engine           | performance               |
|------------------|---------------------------|
| maud             | 332 ns/iter(+/- 20)       |
| horrorshow       | 336 ns/iter(+/- 324)      |
| complicated_maud | 958 ns/iter(+/- 140)      |
| tera             | 7,317 ns/iter(+/- 333)    |
| liquid           | 16,319 ns/iter(+/- 921)   |
| handlebars       | 17,958 ns/iter(+/- 1,041) |
> Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
> Linux x 4.12.14-300.fc26.x86_64 #1 SMP Wed Sep 20 16:28:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
> rustc 1.22.0-nightly (3c96d40d3 2017-09-28)
----------
Template engines
- maud 0.17.1 (local)
- handlebars 0.29.1
- horrorshow 0.6.2
- …
=> Update dependencies for benchmarks

rust-toolchain
This file makes `rustup` select the nightly toolchain for this project, as it
requires. See https://github.com/rust-lang-nursery/rustup.rs/tree/533f09818fff23ba55a7c60474f3798d41bdd69d#the-toolchain-file
=> Enforce nightly toolchain

README.md
I'll leave the decision to keep or remove the existing ‘API reference’ link to you.
=> Add conventional docs.rs badge

maud/tests/control_structures.rs, maud_macros/src/build.rs, maud_macros/src/lib.rs, maud_macros/src/parse.rs
Instead of a `kind` field containting a `TokenNode` variant, a
TokenTree is now an enum with variants of different types (Literal, Op,
Term, etc). Note that a TokenTree could be a sequence of TokenTrees if it is a
Group variant.
Other notes:
I'm unsure about the set_span call in Builder::emit_if, but I did not want to
throw away the passed in Span.
Parsing relies on destructuring references to the values associated with
TokenTree enum variants
Refs #121
=> Refactor to keep up with changes to proc_macro

maud_lints/src/util.rs
refs: https://github.com/rust-lang/rust/pull/49894
closes: #125
=> maud_lints: replace usage of InternedString by LocalInternedString

.travis.yml, maud/Cargo.toml, maud/src/lib.rs
It looks similar to the Rocket implementation, and functionally is also similar:
a syncronous response for PreEscaped<String>
Refs #135
=> impl Responder for actix-web framework

maud/tests/basic_syntax.rs, maud/tests/control_structures.rs, maud_extras/lib.rs, maud_macros/src/ast.rs, maud_macros/src/generate.rs, maud_macros/src/parse.rs
Maud now requires braces around the body of an HTML element. For example, this code
```rust
html! {
h1 a href="/" "Pinkie Pie's awesome website"
div#main (contents)
}
```
must now be written as
```rust
html! {
h1 {
a href="/" { "Pinkie Pie's awesome website" }
}
div#main { (contents) }
}
```
This change was made to address usability issues, as well as improve visual harmony with surrounding Rust code.
Omitting the braces around an element body can reduce clutter. The feature is also easy to implement, and does not introduce ambiguity in the formal grammar.
However, over the last few months I have found many arguments for removing the feature:
* In #117, a user questioned why `label "Email" for="email"` didn't work. If we had required braces around the body, then it would be clear why …
=> Require braces around the body of an element

benchmarks/Cargo.lock, benchmarks/benches/liquid.rs
Use of liquid::Object instead of liquid::Context and use of
Value::scalar instead of Value::Str and Value::Num. Changes to how the
parse() method is called.
=> Fixed benchmarks for liquid 0.15.0

maud_macros/src/parse.rs
Fixes #91.
To avoid erroneously preventing elements which are actually meant to be
called `if` from being used, this is only a warning, with a suggestion
of the template syntax.
=> Added warning when elements have keyword names

maud/src/lib.rs
Whenever I used `@for` of any kind in the returned Markup, Actix detected the content type as `application/octet-stream`, which prevented the browser from displaying it as html.
This PR explicitly sets content-type to "text/html" in the Actix feature handler, and fixes the above issue.  I don't see any reason why this would be incorrect, because all Markup instances are html.  One adjustment might be to explicitly set encoding to utf-8. Let me know if you'd prefer that.
=> Set default content-type html for actix feature

maud/Cargo.toml, maud/src/lib.rs
The default features have also been disabled since they're unused by maud and caused issues when another dependency uses a different version of ring than actix-web.
=> Bumped actix-web version

docs/content/web-frameworks.md
`actix-web` changed its API in the recent 1.0 release; this updates the example in the Web Frameworks section of the documentation to use the new API.
=> Update actix-web support documentation.

benchmarks/Cargo.lock, maud_macros/Cargo.toml
Closes #178 
Not much needed to be done? I ran cargo test and all the tests passed, so I think that it's fine. Not entirely sure if that was all that needed to be done, however.
=> Upgrade syn to 1.0.8. Upgrade matches to 0.1.8

CHANGELOG.md, docs/content/web-frameworks.md, maud/Cargo.toml, maud/src/lib.rs
Cheers,
With the advent of async, actix-web started using futures in their APIs and traits, unfortunately resulting in breaking changes within the Responder trait which maud implements.
I have added support for the newest version of actix-web while trying to still support version 1, since most users have probably not yet migrated to the newest version.
In order to do so I added the trait `actix-web-2` feature and the `actix-web-2-dep` dependency in order to avoid name clashes. Unfortunately enabling the feature also depends on the `futures` crate, since it is used to implement the Responder trait. I also mentioned said support in the web-framework documentation. I have not added any tests, since there were no actix-web tests I could modify. I have verified that this change works within my …
=> actix-web >= 2.0.0 support

docs/src/main.rs, docs/src/page.rs, docs/src/views.rs
The documentation builder is an executable crate, so crate-level visibility doesn't add much.
=> Remove #![feature(crate_visibility_modifier)]

maud/src/lib.rs
See rust-lang/rust#71420.
This doesn't need a release (or a changelog entry) as it just fixes a warning.
=> Silence "specialization is incomplete" warning

maud_macros/Cargo.toml, maud_macros/src/generate.rs, maud_macros/src/lib.rs
This mostly implements lambda-fairy/maud#191.
In general this is done (it builds, tests pass).
To give an overview of the changes:
All internal types are now using `proc_macro2` instead of `proc_macro` **except** [ast.rs](https://github.com/lambda-fairy/maud/blob/master/maud_macros/src/ast.rs) and [parse.rs](https://github.com/lambda-fairy/maud/blob/master/maud_macros/src/parse.rs) as they make heavy use of the location information of spans, which `proc_macro2::Span` cannot provide (yet).
I did it this way, as this avoids excessive conversions between the 2 crates. As the api surface is (mostly) the same i think this will be fine.
I tried to keep actual type-conversions between `proc_macro` and `proc_macro2` to a minimum.
@lambda-fairy if you also could just look over the PR again style …
=> Switch to 3rd party `quote` macro

benchmarks/Cargo.lock, maud_macros/Cargo.toml, maud_macros/src/generate.rs
- Remove crates.io `matches` in favor of the `std` version
- Fix Clippy warning by changing a `match ... { ... }` to `matches!(...)`
=> Use `std::matches!`

maud/src/lib.rs
Closes #188
Blocked By #187
I opted here to have specialization behind its own feature, and to turn that on as part of unstable. Ideally, this should mean that there's a nice catch-all for people that are happy to opt-in to unstable features at large, and it's easier to clean up as specialization stabilizes.
Once #187 is taken care of, I'll rebase this onto the main branch.
=> Specialization Feature

.travis.yml, README.md, benchmarks/Cargo.toml, maud/Cargo.toml, maud/build.rs, maud/src/lib.rs, maud/tests/errors.rs, rust-toolchain
Infer whether nightly features are available using `rustc_version`. If this fails, assume stable.
Closes #214
=> Enable stable support 🎉

maud/Cargo.toml, maud/build.rs
version_check has fewer dependencies, and is already used by proc-macro-error and Rocket.
=> Switch to version_check

.travis.yml
This cuts the CI time in half (5:45 → 3:13).
=> Test `--all-features` separately

.travis.yml
I would expect that most people reading the docs are using the crates.io version, not trunk.
=> Only deploy documentation when a release is tagged

.travis.yml, CHANGELOG.md, maud/Cargo.toml, maud/examples/actix.rs, maud/src/lib.rs
- adds actix-web v3 support
- retains v2 support
- thins deps by using futures-util
=> Add actix-web v3 support

.travis.yml
It seems a lot faster – the "All features" build is ~ 1:45 instead of ~ 3:15.
=> Enable LXD for faster builds

maud/tests/basic_syntax.rs, maud/tests/control_structures.rs, maud/tests/misc.rs, maud/tests/splices.rs, maud/tests/warnings/keyword-without-at.rs, maud/tests/warnings/keyword-without-at.stderr, maud/tests/warnings/keyword_names_without_@.rs
- Call `.into_string()` later
- Rename UI test to match Rust convention
=> Clean up tests

CHANGELOG.md, docs/content/elements-attributes.md, docs/content/splices-toggles.md, maud/tests/basic_syntax.rs, maud_macros/src/parse.rs
Maud no longer requires `?` after an empty attribute. For example, this code
```rust
html! {
input type="checkbox" checked? disabled?[is_disabled];
}
```
can now be written as
```rust
html! {
input type="checkbox" checked disabled[is_disabled];
}
```
The old syntax is still allowed, but soft-deprecated. It will be removed in some future release (TBD).
The `?` was necessary back when braces were optional, such that a bare identifier (e.g. `title`) could mean either an attribute or an element.
But with #137 making braces mandatory, there's no need for the `?` anymore – it is perfectly unambiguous without it.
=> Make the `?` suffix for empty attributes optional

README.md, docs/content/control-structures.md, docs/content/elements-attributes.md, docs/content/getting-started.md, docs/content/index.md, docs/content/partials.md, docs/content/render-trait.md, docs/content/splices-toggles.md, docs/content/text-escaping.md, docs/content/web-frameworks.md
mdformat will preserve semantic line breaks, so we may as well commit to using them.
cc #231
=> Switch documentation to semantic line breaks

CHANGELOG.md
I don't think they add much, and they conflict with mdformat which escapes square brackets (executablebooks/mdformat#112).
cc #231
=> Remove [Foo] tags from changelog

doctest/build.rs
=> Remove `#![feature(extended_key_value_attributes)]`

CHANGELOG.md, maud/src/lib.rs, maud_htmlescape/lib.rs, maud_macros/src/lib.rs
Removed references to `std` and replaced them with references to `core` and `alloc`.
Tests still use `std`.
=> Using no_std + alloc

CHANGELOG.md, docs/content/web-frameworks.md, doctest/Cargo.toml, maud/Cargo.toml, maud/src/lib.rs
This introduces support for Tide by implementing `From` over markup.
Unlike other frameworks, Tide does not seem to provide e.g. a trait
which could instead be implemented. However as demonstrated, this
alternative results in a simple, ergonomic interface.
Consumers may leverage Tide support by using the "tide" feature.
=> Tide support

CHANGELOG.md, docs/content/web-frameworks.md, doctest/Cargo.toml, maud/Cargo.toml, maud/src/lib.rs
This PR adds support for [`axum`](https://docs.rs/axum/0.1.3/axum/)
=> Add axum support

maud/Cargo.toml
This ensures that maud itself doesn't dictate what features an author might like to use.
=> ensure tide default-features are disabled

docs/Makefile
Looks like GitHub's release feature doesn't create annotated tags by default.
=> Fix docs version indicator to include unannotated tags

CHANGELOG.md, docs/content/elements-attributes.md, docs/content/splices-toggles.md, maud/Cargo.toml, maud/tests/basic_syntax.rs, maud/tests/splices.rs, maud_htmlescape/Cargo.toml, maud_macros/Cargo.toml
Closes #308
Technically, the `.class` shorthand doesn't need a preceding space, but I add them anyway for consistency.
=> Update to Rust 2021

docs/content/elements-attributes.md, docs/content/splices-toggles.md, maud/tests/basic_syntax.rs, maud/tests/splices.rs
On reflection, the extra spaces around classes feels weird to me. Let's revert that (but keep the 2021 edition migration in place).
=> Partially revert #309 for class shorthand

CHANGELOG.md, docs/content/web-frameworks.md, doctest/Cargo.toml, maud/Cargo.toml, maud/src/lib.rs
The Iron framework hasn't been updated in a long time. It still uses outdated versions of libraries like futures 0.1, hyper 0.12, url 1.7. We can clean up the repo by removing it. This will also slightly speed up CI.
=> Remove Iron support

.github/workflows/ci.yml
Nightly rustfmt is needed for the `imports_granularity` option.
=> Switch rustfmt to nightly

CHANGELOG.md, docs/content/elements-attributes.md, maud/tests/basic_syntax.rs, maud/tests/warnings/void-element-slash.rs, maud/tests/warnings/void-element-slash.stderr, maud_macros/src/parse.rs
The following syntax will no longer work:
```rust
html! {
br /
link rel="stylesheet" href="styles.css" /
}
```
This should be changed to the following:
```rust
html! {
br;
link rel="stylesheet" href="styles.css";
}
```
The `;` syntax was introduced in #96; the rationale for it can be found there.
Removing support for the older `/` syntax will simplify the API surface, and allow for the space to be used for other things.
=> Disallow slashes (`/`) in void elements

CHANGELOG.md, docs/Cargo.lock, docs/content/render-trait.md, docs/content/splices-toggles.md, maud/Cargo.toml, maud/src/lib.rs, maud_macros/src/generate.rs
=> Remove blanket `Render` impl for `T: Display`

.github/workflows/ci.yml, docs/content/elements-attributes.md
Per rust-lang/cargo#6424, `cargo check` doesn't actually run the doctests. So we need `cargo test` for this to work.
=> Run doctests again

CHANGELOG.md, docs/content/web-frameworks.md, doctest/Cargo.toml, maud/Cargo.toml, maud/src/lib.rs
Together with the new 0.4 release of `axum` we made a new crate called
[`axum-core`]. `axum-core` has a small API and is less likely to receive
breaking changes. Therefore its recommended for libraries to depend on
`axum-core` instead of `axum`.
So this updates `maud` to use `axum-core`.
Note this is a breaking change since `axum-core` requires `axum` 0.4.
[`axum-core`]: https://crates.io/crates/axum-core
=> Update to axum-core 0.1

maud/src/lib.rs
Implicitly-named format args were introduced in 69649421686a16206d55eb31634f2b77f8aa504e as part of the work on #320, but it does not appear that feature will land until Rust 1.58. Explicitly naming the args ensures that the Maud works on non-Nightly builds of Rust.
=> Use explicitly-named args in `impl_render_with_display`

CHANGELOG.md, maud/src/lib.rs
=> Add `maud::display`

maud/src/escape.rs, maud_macros/src/escape.rs
The symlink doesn't work on Windows, and breaks NixOS builds.
Closes #343
=> Don't symlink the escaper module

RELEASE_PROCESS.md
The GitHub Releases feature creates lightweight tags, not annotated tags.
=> Add `git tag -a` to release process

docs/Cargo.lock, maud/Cargo.toml, maud/src/lib.rs
itoa 0.4 used `mem::uninitialized`, which is a very bad API as it's way of doing uninitialized memory goes against Rust's memory model. Starting from 1.64 it's slower because of the [forced memory initialization](https://github.com/rust-lang/rust/pull/99182/) it does to avoid the unsoundness
=> Bump itoa to v1

maud/src/lib.rs, maud/tests/misc.rs, maud_macros/src/generate.rs
This may not be something you're interested in merging. No hard feelings if you close this outright. :-)
I found for my use case that I needed to write `display(...)` in a lot of places, especially in cases where I was using external types (especially the many datetime formatting types from `icu`).
This PR adds [autoref-based specialization](http://lukaskalbertodt.github.io/2019/12/05/generalized-autoref-based-specialization.html) to the `html!` macro such that it will choose a type's `Render` implementation if it is available, and use `Display` as a fallback.
The blanket impl of `Render for T where T: Display` was removed in #271 for good reasons, and I will try to justify this PR in terms of those reasons:
- #266 (Impl Render for borrows): This PR does not add any new blanket impls of …
=> Render with Display using autoref specialization

docs/content/control-structures.md, docs/content/elements-attributes.md, docs/content/faq.md, docs/content/getting-started.md, docs/content/index.md, docs/content/partials.md, docs/content/render-trait.md, docs/content/splices-toggles.md, docs/content/text-escaping.md, docs/content/web-frameworks.md
Using the same rationale as [this proposal](https://discuss.python.org/t/one-sentence-per-line-for-peps-and-more/13920):
> However, “practicality beats purity”, and the practical downsides in actual use—increased tedious effort and cognitive burden, increased learning curve (especially for those who aren’t native English writers), difficulty of consistently enforcing, impossibility to check or automate with tooling, introducing choppy, poetry-like flow when reading, greater total vertical space consumption, more complex to review/suggest—weight strongly against it. From our experience, OSPL is a much better solution in practice, which seems to be the case for others as well, as the authors are currently not aware of any large projects that have formally adopting and consistently used …
=> Switch documentation to one-sentence-per-line

docs/content/web-frameworks.md
Axum was missing in the list at the top of the file.
Not sure if the other frameworks should be added to `index.md`,
only Rocket and Actix are mentioned there.
=> Add axum to the list of frameworks in docs

CHANGELOG.md, maud/src/lib.rs, maud/tests/misc.rs
Tests was broken before the change, I'm not sure if I should fix them. But `cargo test misc` works.
=> impl Default for PreEscaped

CHANGELOG.md, docs/content/render-trait.md, maud/src/lib.rs
=> Remove `AsRef<str>` restriction from structs

CHANGELOG.md, maud/tests/basic_syntax.rs, maud_macros/src/ast.rs, maud_macros/src/parse.rs
The parser now accepts `TokenTree::Literal` as names for attributes.
To prevent the `name_to_string` function from showing and escaping the surrounding `"` of a string literal the string representation is trimmed first. This should not affect how other literals work which means that both `"name"="true"` and `123="true"` would be valid.
This also addresses the PR request in #194
=> Accept literals in attribute names

docs/Cargo.lock, maud_macros/Cargo.toml
This PR bumps the `syn` dependency to version 2.0.0
It also removes the default features of `proc-macro-error` (which weren't used) to remove the transitive dependency on `syn` 1.0.0.
=> Upgrade to `syn` 2.0.0

CHANGELOG.md, docs/content/web-frameworks.md, doctest/Cargo.toml, maud/Cargo.toml, maud/src/lib.rs
=> Support `axum` v0.7 through `axum-core` v0.4 and `http` v1

CHANGELOG.md, docs/content/web-frameworks.md, doctest/Cargo.toml, maud/Cargo.toml, maud/src/lib.rs
As title; updates rocket support to the (recently stabilized) 0.5 version.
=> Update rocket support to v0.5

maud/tests/basic_syntax.rs, maud/tests/warnings/non-string-literal.stderr, maud_macros/src/parse.rs
This is a fix for the bug mentioned in https://github.com/lambda-fairy/maud/pull/396#issuecomment-1811008846. 
This is similar to #336 and also addresses #335, se the test for examples of what is now possible
The implications mentioned in https://github.com/lambda-fairy/maud/issues/335#issuecomment-1094247196 are not addressed here, but for now this fixes the bug that #396 created
=> Parse many literals along side idents in names

CHANGELOG.md, docs/content/web-frameworks.md, doctest/Cargo.toml, maud/Cargo.toml, maud/src/lib.rs
This implements `warp::Reply` for `Markup`, making it possible to return it from a handler and making *maud* more pleasing to use with *warp*.
=> Warp Integration: Yet another web framework support

CHANGELOG.md, doctest/Cargo.toml, maud/Cargo.toml
axum 0.8 uses axum-core 0.5, which is not semver-compatible with 0.4 and thus doesn't get picked up.
Not sure if there's more to do.
Fixes #453
=> Bump axum-core to 0.5 for axum 0.8 compatibility

maud_macros/src/parse.rs
=> Abort when `else` is used without `@` (#449)

maud/tests/warnings/attribute-missing-value.stderr, maud/tests/warnings/class-shorthand-missing-value.stderr, maud/tests/warnings/elements-in-attributes.rs, maud/tests/warnings/elements-in-attributes.stderr, maud_macros/src/ast.rs, maud_macros/src/generate.rs
Fixes a regression from #412. Alternate implementation of #459.
The following code was allowed, and this PR fixes the parser to ban it:
```rust
html! {
a href={ b {} } {}
}
```
=> Disallow elements in attributes (redux)

maud/tests/warnings/dynamic-attribute-names.rs, maud/tests/warnings/dynamic-attribute-names.stderr, maud_macros/src/ast.rs, maud_macros/src/generate.rs
They were already disallowed before, but this also removes them from the AST.
=> Explicitly disallow dynamic attribute names

maud/tests/warnings/non-string-literal.stderr, maud_macros/src/ast.rs
This fixes the last regression from #412.
=> Re-disallow integer literals

CHANGELOG.md, docs/content/web-frameworks.md, doctest/Cargo.toml, maud/Cargo.toml, maud/src/lib.rs
Support is gated behind the poem-3 feature.
=> feat: Add support for web framework poem@3

maud/src/lib.rs
I have not bother benchmarking, but I believe avoiding allocating a HashMap will be easier to optimize and/or faster at runtime.
=> Avoid allocation when converting to axum's Response
