lambda-fairy/maud

- maud_macros/src/parse.rs
This is a fix to issue #84 
Tasks done :
- Add a Parser::error() method with a similar signature to the error!() macro
- Change all instances of error!(...) to return self.error(...)
- Remove the error!() macro
> Remove 'error!' macro

- benchmarks/Cargo.lock
- benchmarks/Cargo.toml
- benchmarks/benches/askama.rs
For [Askama template rendering engine](https://github.com/djc/askama)
Also updates Cargo.lock
> Add Askama benchmark

- maud/tests/basic_syntax.rs
- maud/tests/control_structures.rs
- maud/tests/misc.rs
- maud/tests/splices.rs
- maud_extras/lib.rs
- maud_macros/src/lib.rs
This fixes the failing build for `nightly-2018-04-26`.
Thanks for the hint @lfairy! Somehow I just didn't fully read the error message :man_facepalming: . I'm not very familiar with Rust so let me know if I did something dumb.
Resolves #123
> Enable proc_macro_non_items feature flag

- CHANGELOG.md
- benchmarks/benches/complicated_maud.rs
- benchmarks/benches/maud.rs
> fix: update benchmarks to build with 0.18.x, document required compiler feature flags change

- maud/Cargo.toml
> bump rocket to 0.4

- docs/content/basic-syntax.md
> Add example to docs of custom element

- maud_macros/src/lib.rs
This implements lambda-fairy/maud#190
> Replace Span::def_site and remove #![feature(proc_macro_def_site)]

- .travis.yml
- benchmarks/Cargo.toml
- maud/Cargo.toml
> Add an off-by-default 'unstable' flag

- maud/src/lib.rs
> Put specialized impls in a logical order

- .travis.yml
- benchmarks/benches/askama.rs
- benchmarks/benches/complicated_maud.rs
- benchmarks/benches/handlebars.rs
- benchmarks/benches/horrorshow.rs
- benchmarks/benches/liquid.rs
- benchmarks/benches/maud.rs
- benchmarks/benches/tera.rs
- docs/src/main.rs
- docs/src/page.rs
- docs/src/views.rs
- maud/src/lib.rs
- maud/tests/absolute_paths.rs
- maud/tests/basic_syntax.rs
- maud/tests/control_structures.rs
- maud/tests/splices.rs
- maud_htmlescape/lib.rs
- maud_macros/src/ast.rs
- maud_macros/src/generate.rs
- maud_macros/src/lib.rs
- maud_macros/src/parse.rs
> Add rustfmt and format the project

- benchmarks/benches/complicated_maud.rs
- benchmarks/benches/maud.rs
- docs/src/main.rs
- maud/src/lib.rs
- maud/tests/absolute_paths.rs
- maud/tests/basic_syntax.rs
- maud/tests/control_structures.rs
- maud/tests/misc.rs
- maud/tests/splices.rs
- maud/tests/warnings/keyword_names_without_@.rs
- maud/tests/warnings/keyword_names_without_@.stderr
- maud_macros/src/lib.rs
> Remove `#![feature(proc_macro_hygiene)]`

- .travis.yml
- benchmarks/Cargo.lock
- docs/Cargo.lock
- maud/Cargo.toml
- maud/build.rs
- maud/src/lib.rs
- maud_macros/src/generate.rs
> Avoid unstable specialization with this one weird trick!

- docs/content/getting-started.md
- docs/content/web-frameworks.md
> Update documentation to account for stable support

- docs/Makefile
- docs/src/main.rs
- docs/src/views.rs
- docs/styles.css
This will be helpful for debugging once #226 lands.
> Add a version string to the documentation

- docs/content/elements-attributes.md
> Improve "elements and attributes" documentation

- README.md
- maud/Cargo.toml
- maud_macros/Cargo.toml
> Remove Travis status badges

- .github/workflows/ci.yml
- maud/tests/control_structures.rs
- maud/tests/splices.rs
> Enable --all-targets for Clippy

- CHANGELOG.md
- maud/src/lib.rs
> Generalize Into impl to From

- docs/content/render-trait.md
> Fix pulldown-cmark/ammonia example in docs

- maud/tests/warnings/attribute-missing-value.rs
- maud/tests/warnings/attribute-missing-value.stderr
- maud/tests/warnings/class-shorthand-missing-value.rs
- maud/tests/warnings/class-shorthand-missing-value.stderr
- maud/tests/warnings/element-missing-body.rs
- maud/tests/warnings/element-missing-body.stderr
- maud/tests/warnings/non-string-literal.rs
- maud/tests/warnings/non-string-literal.stderr
> Add more UI tests

- maud/tests/warnings/non-string-literal.rs
- maud/tests/warnings/non-string-literal.stderr
- maud_macros/src/ast.rs
- maud_macros/src/generate.rs
- maud_macros/src/parse.rs
> Improve error message for non-string literals

- docs/Makefile
- docs/src/bin/build_nav.rs
- docs/src/bin/build_page.rs
- docs/src/lib.rs
- docs/src/page.rs
- docs/src/views.rs
Move page and nav builders to separate modules.
> Refactor book builder

- docs/src/bin/build_nav.rs
- docs/src/bin/build_page.rs
- docs/src/page.rs
- docs/src/string_writer.rs
- docs/src/views.rs
- maud/src/lib.rs
- rustfmt.toml
> Enforce merged imports

- docs/content/index.md
> Remove "blazing"

- maud_macros/Cargo.toml
> Bump dependency proc-macro2 to 1.0.23

- .github/workflows/ci.yml
- CONTRIBUTING.md
Also rename the "Examples" build to "Doctest" to clarify what it does.
> Document that the `doctest` crate might need updating

- CHANGELOG.md
- maud/benches/complicated_maud.rs
- maud/src/lib.rs
- maud/tests/splices.rs
- maud_macros/src/lib.rs
It's not documented anywhere, and `cargo expand` does the same thing.
> Remove `html_debug!`

- CHANGELOG.md
- doctest/Cargo.toml
- maud/Cargo.toml
This is required for axum 0.6 support
> Bump axum-core to 0.3.0

- docs/src/lib.rs
> Change `#![feature(once_cell)]` to `lazy_cell`

- CHANGELOG.md
- docs/Cargo.lock
- docs/src/bin/build_page.rs
- maud/Cargo.toml
- maud/src/lib.rs
- maud_macros/Cargo.toml
- maud_macros/src/lib.rs
> Release 0.25.0

- Cargo.toml
https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions
> Set resolver explicitly in workspace config

- docs/content/splices-toggles.md
This PR concerns issue #389 and tries to clear up some ambiguity in the documentation regarding toggles.
> Update documentation regarding toggles (#389)

- docs/content/web-frameworks.md
- doctest/Cargo.toml
- maud/Cargo.toml
- maud/src/lib.rs
Adds support for Submillisecond, a Lunatic web framework
> feat: Add support for Submillisecond web framework

- maud/src/lib.rs
Tiny QoL improvement for Actix Web users.
Allows use in `HttpResponse::Ok().body(markup)` position without needing to `.0`.
> Implement MessageBody for Markup

- maud/tests/warnings/keyword-without-at.rs
- maud/tests/warnings/keyword-without-at.stderr
- maud_macros/src/ast.rs
> Error when `else` is used without `@`
